apiVersion: v1
kind: Service
metadata:
  name: servicio-node-port
  labels:
    app: back 
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 9000 # puerto en el que escuchara el servicio
      targetPort: 80 # puerto por el que escucha la imagen a desplegar
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: cont-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80 
       