apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-front 
spec:
  selector:
    app: nginx-front
  ports:
    - protocol: TCP
      port: 8000 # puerto en el que escuchara el servicio
      targetPort: 80 # puerto por el que escucha la imagen a desplegar