apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: nginx-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-front
  template:
    metadata:
      labels:
        app: nginx-front
    spec:
      containers:
        - name: cont-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80 
       