apiVersion: v1
kind: Pod
metadata:
  name: manifiesto-con-multiples-pod-01
  labels:
    app: frontend
    env: dev     
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: manifiesto-con-multiples-pod-02
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: manifiesto-con-multiples-pod-03
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP