apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test-1
  labels:
    app: rs-test-1  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-labels
  template:
    metadata:
      labels:
        app: pod-labels
    spec:
      containers:
        - name: cont-1
          image: python:3.7-alpine
          command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8082']
        - name: cont-2
          image: python:3.7-alpine
          command: ['sh', '-c', 'echo cont2 > index.html && python -m http.server 8083']